# Generated by Django 5.2.8 on 2026-01-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('finished', 'Encerrado')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='rental',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
