# Generated by Django 5.2.8 on 2026-01-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rental_daily_price_rental_status_rental_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='weekly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
