# Generated by Django 5.2.8 on 2026-01-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_alter_rental_weekly_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='km_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
