# Generated by Django 5.2.8 on 2026-01-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_alter_rental_km_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='status',
        ),
        migrations.AddField(
            model_name='rental',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
