# Generated by Django 5.2.8 on 2026-01-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cnh', models.CharField(max_length=20, unique=True, verbose_name='Cnh')),
            ],
        ),
    ]
