# Generated by Django 5.2.8 on 2026-01-16 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('plate', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('km', models.IntegerField(default=0, verbose_name='Quilometragem')),
                ('status', models.CharField(choices=[('operacional', 'Operacional'), ('manutencao', 'Em Manutenção')], default='operacional', max_length=20, verbose_name='Status')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da compra')),
                ('financed', models.BooleanField(default=False, verbose_name='Financiado')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('REVISAO', 'Revisão'), ('OLEO', 'Troca de óleo'), ('FREIO', 'Freios'), ('CORREIA', 'Correia'), ('SUSPENSAO', 'Suspensão'), ('OUTRO', 'Outro'), ('PNEU', 'Troca de pneus')], max_length=20)),
                ('km', models.PositiveIntegerField(help_text='Quilometragem do veículo no momento da manutenção')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenances', to='cars.car')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['car', 'date'], name='cars_mainte_car_id_c9c380_idx'), models.Index(fields=['car', 'km'], name='cars_mainte_car_id_ecf2c2_idx')],
            },
        ),
    ]
