# Generated by Django 5.2.8 on 2025-11-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('plate', models.CharField(max_length=10, unique=True)),
                ('year', models.IntegerField()),
                ('km', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('alugado', 'Alugado'), ('manutencao', 'Em Manutenção')], default='disponivel', max_length=20)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('financed', models.BooleanField(default=False)),
            ],
        ),
    ]
