# Generated by Django 5.2.8 on 2026-01-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('plate', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('km', models.IntegerField(default=0, verbose_name='Quilometragem')),
                ('status', models.CharField(choices=[('operacional', 'Operacional'), ('manutencao', 'Em Manutenção')], default='operacional', max_length=20, verbose_name='Status')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da compra')),
                ('financed', models.BooleanField(default=False, verbose_name='Financiado')),
            ],
        ),
    ]
