# Generated by Django 5.2.8 on 2026-01-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='financed',
            field=models.BooleanField(default=False, verbose_name='Financiado'),
        ),
        migrations.AlterField(
            model_name='car',
            name='km',
            field=models.IntegerField(default=0, verbose_name='Quilometragem'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate',
            field=models.CharField(max_length=10, unique=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='car',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da compra'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('alugado', 'Alugado'), ('manutencao', 'Em Manutenção')], default='disponivel', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(verbose_name='Ano'),
        ),
    ]
