# Generated by Django 5.2.8 on 2026-01-26 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maintenance',
        ),
    ]
