# Generated by Django 5.2.8 on 2026-01-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_financed_alter_car_km_alter_car_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('operacional', 'Operacional'), ('manutencao', 'Em Manutenção')], default='operacional', max_length=20, verbose_name='Status'),
        ),
    ]
